# SPDX-FileCopyrightText: 2021 Konrad Weihmann
# SPDX-License-Identifier: GPL-2.0-only
name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:  ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: prepare
      run: |
        python3 -m pip install --upgrade pip
        pip install --upgrade setuptools 
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: test (pytest)
      run: pytest
      shell: bash
    - name: build
      run: python3 setup.py build sdist
    - name: install
      run: python3 setup.py install --user
    - name: test (installed)
      run: |
        shellexeclist --help
        shellexeclist gitlab --help
        shellexeclist github --help
        shellexeclist mock --help
        tar -tvf dist/shellexeclist-*.tar.gz | grep LICENSE
        tar -tvf dist/shellexeclist-*.tar.gz | grep README.md
      shell: bash